### PR TITLE
add mutex, update of #123

### PR DESCRIPTION
**Pull request by SaintMercury**
Updated and rebased version of the following PR

https://github.com/effil/effil/pull/123

Adds mutexes to lua api and fixes the tests (on windows)

### CODE REVIEW

**Comment by mihacooper** [comment]
As far, as I remember there is a problem in how we implemented a thread cancellation - using exceptions. The problem appeared when I tried to add one more additional test: check what will happen if we cancel a thread hanged on mutex (inside callback). It causes invalid behaviour (SEGFAULT if I  remember it right).

So, first of all we need to change the implementation of thread cancellation.

**Comment by SaintMercury** [comment]
Ah, I understand. I shall try to test when I can.

Do you propose a total refactor? I noticed on windows that the LuaCancelException thrown in threading.cpp never actually seems to get caught.

**Comment by mihacooper** [comment]
yep, we need to do something with current thread cancellation implementation.
I see only two ways: get rid of cancellation functionality or implement it using normal exceptions(lua error()) but in that case cancel error can be catched by `pcall` method

**Comment by SaintMercury** [comment]
After doing some lite research into how other languages handle thread cancellation.

Java deprecated the ability to cancel threads, and Python does not as well.

C# allows this via throwing an exception in the thread that can be caught.

Golang and Rust don't support it either.

It looks like most places recommend passing in some signal channel and handling the cancellation/termination based upon that.


I'd propose probably just disallowing the cancel behaviour natively, and having users design ways to cancel threads.

**Comment by mihacooper** [comment]
I have decided to left cancellation behaviour for right now, but implemented it using regular lua error: https://github.com/effil/effil/pull/177

After this PR will be merged, I will commit mutex PR. So, now I close this PR.

**Pull request closed without merging**
